sonar.projectKey=clarity-fintech_CLRTY-Quality-Gate
sonar.projectName=CLRTY-Quality-Gate
sonar.sources=src
sonar.tests=tests
sonar.typescript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8
